steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_IMAGE}
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_IMAGE}

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_IMAGE}
      - --region=${_REGION}
      - --platform=managed
      - --port=8080
      - --allow-unauthenticated
      - --timeout=3600
      - --set-env-vars=KOSHIBAR_PASSWORD=KOSHIBAR,WS_PATH=/Koshibar/Shadowsocks
      - --min-instances=0
      - --max-instances=10
      - --concurrency=80

images:
  - ${_IMAGE}

substitutions:
  _SERVICE: koshibar-shadowsocks
  _REGION: europe-west1
  _IMAGE: europe-west1-docker.pkg.dev/$PROJECT_ID/koshibar/koshibar-shadowsocks:latest

options:
  logging: CLOUD_LOGGING_ONLY
